version: '3'
services:
  orangehrm:
    image: orangehrm/orangehrm
    ports:
      - 7005:80
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    # platform: linux/x86_64   # this line is only required if you are using mac-m1 chip
  db:
    image: mysql:5.7
    ports:
      - 7001:3306
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - orangehrm-db:/var/lib/mysql
    # platform: linux/x86_64 # this line is only required if you are using mac-m1 chip

volumes:
  orangehrm-db:
